<a href="https://colab.research.google.com/github/Kishan-kp-ai/Linkific-Tasks/blob/main/Day%205/practicePandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("student_data.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df

      Name   Age  Gender  Marks       City
0    Rahul  20.0    Male   85.0      Hubli
1    Priya  21.0  Female   92.0  Bangalore
2     Amit  19.0    Male   76.0     Mysore
3    Sneha  20.0  Female   88.0      Hubli
4    Kiran  22.0    Male    NaN    Dharwad
5   Anjali  21.0  Female   95.0  Bangalore
6    Rohit  23.0    Male   72.0    Belgaum
7     Neha  20.0  Female   81.0      Hubli
8    Vijay   NaN    Male   64.0     Mysore
9    Pooja  22.0  Female   89.0    Dharwad
10   Arjun  21.0    Male   78.0      Hubli
11   Meena  19.0  Female   91.0  Bangalore
12  Suresh  25.0    Male   55.0        NaN
13   Divya  20.0  Female   84.0     Mysore
14  Nikhil  22.0    Male   73.0      Hubli
15   Kavya  21.0  Female   97.0    Dharwad
16   Manoj  23.0    Male    NaN  Bangalore
17    Asha  20.0  Female   86.0      Hubli
18  Deepak  24.0    Male   61.0     Mysore
19    Riya  22.0  Female   90.0    Belgaum

In [5]:
print("First 5 rows:")
display(df.head())

First 5 rows:

    Name   Age  Gender  Marks       City
0  Rahul  20.0    Male   85.0      Hubli
1  Priya  21.0  Female   92.0  Bangalore
2   Amit  19.0    Male   76.0     Mysore
3  Sneha  20.0  Female   88.0      Hubli
4  Kiran  22.0    Male    NaN    Dharwad

In [6]:
print("Last 5 rows:")
display(df.tail())

Last 5 rows:

      Name   Age  Gender  Marks       City
15   Kavya  21.0  Female   97.0    Dharwad
16   Manoj  23.0    Male    NaN  Bangalore
17    Asha  20.0  Female   86.0      Hubli
18  Deepak  24.0    Male   61.0     Mysore
19    Riya  22.0  Female   90.0    Belgaum

In [8]:
rows, columns = df.shape
print(df.shape)
print("Number of rows:", rows)
print("Number of columns:", columns)

(20, 5)
Number of rows: 20
Number of columns: 5

In [9]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Name      0
Age       1
Gender    0
Marks     2
City      1
dtype: int64

In [10]:
print("Students with marks greater than 80:")
display(df[df["Marks"] > 80])

print("Students older than 21:")
display(df[df["Age"] > 21])

print("Female students:")
display(df[df["Gender"] == "Female"])

print("Students from Hubli:")
display(df[df["City"] == "Hubli"])

print("Female students with marks greater than 80:")
display(df[(df["Gender"] == "Female") & (df["Marks"] > 80)])

Students with marks greater than 80:

      Name   Age  Gender  Marks       City
0    Rahul  20.0    Male   85.0      Hubli
1    Priya  21.0  Female   92.0  Bangalore
3    Sneha  20.0  Female   88.0      Hubli
5   Anjali  21.0  Female   95.0  Bangalore
7     Neha  20.0  Female   81.0      Hubli
9    Pooja  22.0  Female   89.0    Dharwad
11   Meena  19.0  Female   91.0  Bangalore
13   Divya  20.0  Female   84.0     Mysore
15   Kavya  21.0  Female   97.0    Dharwad
17    Asha  20.0  Female   86.0      Hubli
19    Riya  22.0  Female   90.0    Belgaum

Students older than 21:

      Name   Age  Gender  Marks       City
4    Kiran  22.0    Male    NaN    Dharwad
6    Rohit  23.0    Male   72.0    Belgaum
9    Pooja  22.0  Female   89.0    Dharwad
12  Suresh  25.0    Male   55.0        NaN
14  Nikhil  22.0    Male   73.0      Hubli
16   Manoj  23.0    Male    NaN  Bangalore
18  Deepak  24.0    Male   61.0     Mysore
19    Riya  22.0  Female   90.0    Belgaum

Female students:

      Name   Age  Gender  Marks       City
1    Priya  21.0  Female   92.0  Bangalore
3    Sneha  20.0  Female   88.0      Hubli
5   Anjali  21.0  Female   95.0  Bangalore
7     Neha  20.0  Female   81.0      Hubli
9    Pooja  22.0  Female   89.0    Dharwad
11   Meena  19.0  Female   91.0  Bangalore
13   Divya  20.0  Female   84.0     Mysore
15   Kavya  21.0  Female   97.0    Dharwad
17    Asha  20.0  Female   86.0      Hubli
19    Riya  22.0  Female   90.0    Belgaum

Students from Hubli:

      Name   Age  Gender  Marks   City
0    Rahul  20.0    Male   85.0  Hubli
3    Sneha  20.0  Female   88.0  Hubli
7     Neha  20.0  Female   81.0  Hubli
10   Arjun  21.0    Male   78.0  Hubli
14  Nikhil  22.0    Male   73.0  Hubli
17    Asha  20.0  Female   86.0  Hubli

Female students with marks greater than 80:

      Name   Age  Gender  Marks       City
1    Priya  21.0  Female   92.0  Bangalore
3    Sneha  20.0  Female   88.0      Hubli
5   Anjali  21.0  Female   95.0  Bangalore
7     Neha  20.0  Female   81.0      Hubli
9    Pooja  22.0  Female   89.0    Dharwad
11   Meena  19.0  Female   91.0  Bangalore
13   Divya  20.0  Female   84.0     Mysore
15   Kavya  21.0  Female   97.0    Dharwad
17    Asha  20.0  Female   86.0      Hubli
19    Riya  22.0  Female   90.0    Belgaum

In [11]:
print("Summary Statistics:")
display(df.describe())

Summary Statistics:

             Age      Marks
count  19.000000  18.000000
mean   21.315789  80.944444
std     1.634783  12.031685
min    19.000000  55.000000
25%    20.000000  73.750000
50%    21.000000  84.500000
75%    22.000000  89.750000
max    25.000000  97.000000