<a href="https://colab.research.google.com/github/Kishan-kp-ai/Linkific-Tasks/blob/main/Day%208/pandahandlingdatadet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("student_data_65_students_cleaning_project.csv")

df

   Student Name   age  Gender  marks       city Attendance
0       Rahul 1  20.0    Male   85.0      Hubli         76
1       Priya 2  21.0  Female   92.0  Bangalore         89
2        Amit 3  19.0    Male   76.0     Mysore         98
3       Sneha 4  20.0  Female   88.0      Hubli         84
4       Kiran 5  22.0    Male    NaN    Dharwad         80
..          ...   ...     ...    ...        ...        ...
65       Amit 3  19.0    Male   76.0     Mysore         98
66     Kavya 16  21.0  Female   97.0    Dharwad         90
67     Arjun 31  21.0    Male   78.0      Hubli         81
68    Anjali 46  21.0  Female   95.0  Bangalore         88
69     Rahul 61  20.0    Male   85.0      Hubli         97

[70 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  70 non-null     object
 1   age           66 non-null     float64
 2   Gender        70 non-null     object
 3   marks         62 non-null     float64
 4   city          66 non-null     object
 5   Attendance    70 non-null     object
dtypes: float64(2), object(4)
memory usage: 3.4+ KB

In [4]:
df.shape

(70, 6)

In [5]:
df.isnull().sum()

Student Name    0
age             4
Gender          0
marks           8
city            4
Attendance      0
dtype: int64

In [6]:
df.isnull().sum().sum()

np.int64(16)

In [7]:
df[df.isnull().any(axis=1)]

   Student Name   age  Gender  marks       city   Attendance
4       Kiran 5  22.0    Male    NaN    Dharwad           80
7        Neha 8   NaN  Female   81.0      Hubli           90
8       Vijay 9   NaN    Male   64.0     Mysore           76
12    Suresh 13  25.0    Male   55.0        NaN  eighty five
16     Manoj 17  23.0    Male    NaN  Bangalore           73
18    Deepak 19  24.0    Male    NaN     Mysore           93
24     Kiran 25  22.0    Male    NaN    Dharwad           81
28     Vijay 29   NaN    Male   64.0     Mysore           90
29     Pooja 30  22.0  Female   89.0        NaN           70
32    Suresh 33  25.0    Male   55.0        NaN           91
36     Manoj 37  23.0    Male    NaN  Bangalore           86
44     Kiran 45  22.0    Male    NaN    Dharwad           84
48     Vijay 49   NaN    Male   64.0     Mysore           89
52    Suresh 53  25.0    Male   55.0        NaN           88
56     Manoj 57  23.0    Male    NaN  Bangalore           76
64     Kiran 65  22.0    Male    NaN    Dharwad           78

In [8]:
df["age"] = df["age"].fillna(df["age"].median())
df["marks"] = df["marks"].fillna(df["marks"].median())

In [9]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [10]:
df.isnull().sum()

Student Name    0
age             0
Gender          0
marks           0
city            0
Attendance      0
dtype: int64

In [13]:
#dublicate records
df.duplicated().sum()

np.int64(5)

In [14]:
df = df.drop_duplicates()

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.shape

(65, 6)

In [17]:
#feature engineering
df.columns

Index(['Student Name', 'age', 'Gender', 'marks', 'city', 'Attendance'], dtype='object')

In [18]:
df = df.rename(columns={
    "Student Name": "name",
    "age": "age",
    "marks": "marks",
    "city": "city",
    "Attendance": "attendance"
})

In [19]:
df.columns

Index(['name', 'age', 'Gender', 'marks', 'city', 'attendance'], dtype='object')

In [23]:
#handel data type
df.dtypes

name           object
age           float64
Gender         object
marks         float64
city           object
attendance    float64
dtype: object

In [22]:

df["attendance"] = pd.to_numeric(df["attendance"], errors="coerce")
df["attendance"] = df["attendance"].fillna(df["attendance"].median())
df.dtypes

name           object
age           float64
Gender         object
marks         float64
city           object
attendance    float64
dtype: object

In [24]:
df.to_csv("cleaned_student_data.csv", index=False)

In [25]:
print("Shape:", df.shape)
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate records:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (65, 6)
Missing values:
name          0
age           0
Gender        0
marks         0
city          0
attendance    0
dtype: int64

Duplicate records: 0

Data types:
name           object
age           float64
Gender         object
marks         float64
city           object
attendance    float64
dtype: object

In [26]:
df.head(10)

       name   age  Gender  marks       city  attendance
0   Rahul 1  20.0    Male   85.0      Hubli        76.0
1   Priya 2  21.0  Female   92.0  Bangalore        89.0
2    Amit 3  19.0    Male   76.0     Mysore        98.0
3   Sneha 4  20.0  Female   88.0      Hubli        84.0
4   Kiran 5  22.0    Male   85.0    Dharwad        80.0
5  Anjali 6  21.0  Female   95.0  Bangalore        77.0
6   Rohit 7  23.0    Male   72.0    Belgaum        98.0
7    Neha 8  21.0  Female   81.0      Hubli        90.0
8   Vijay 9  21.0    Male   64.0     Mysore        76.0
9  Pooja 10  22.0  Female   89.0    Dharwad        95.0

In [27]:
df.to_csv("cleaned_student_data.csv", index=False)